(() => {
const $=id=>document.getElementById(id),uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const blank=()=>({version:3,id:"",createdAt:null,savedAt:null,event:{name:"Nuova gara di nuoto",date:"",venue:"",notes:"",pathNotes:"",athleteTotal:0,athleteDescription:"",athleteDepartures:[]},timeline:[],officials:[],roleCategories:[],refereeNotes:{briefingAthletes:"",briefingJury:"",checklist:[]}});
let state=blank(),currentSha=null,accessMode="open",dirty=false,editCtx=null;const config=OWStorage.loadGithubConfig();
const status=(t,e=false)=>OWUI.setStatus(t,e),code=v=>String(v||"").trim().replace(/[^a-zA-Z0-9_-]+/g,"-").replace(/^-+|-+$/g,"");
const b64=t=>{const a=new TextEncoder().encode(t);let s="";a.forEach(x=>s+=String.fromCharCode(x));return btoa(s)},unb64=t=>new TextDecoder().decode(Uint8Array.from(atob(String(t||"").replace(/\n/g,"")),c=>c.charCodeAt(0)));
function mark(){dirty=true;$('saveEventBtn').textContent='● Salva';renderHeader()}
function renderHeader(){
  $('eventTitle').textContent=state.event.name||'Gestionale OW';
  const bits=[state.id?`Codice ${state.id}`:'Evento non salvato',state.event.venue,state.event.date,state.event.athleteTotal?`${state.event.athleteTotal} atleti`:null].filter(Boolean);
  $('eventMeta').textContent=bits.join(' · ');
  $('githubBadge').textContent=config.token?'Token API attivo':'Token non inserito';
  $('githubBadge').classList.toggle('connected',!!config.token);
  $('eventAccessBadge').textContent=state.id?`Evento ${state.id}`:'Nessun evento';
  $('eventAccessBadge').classList.toggle('connected',!!state.id)
}
function requireToken(){if(config.token)return true;status('Inserisci il token API aprendo o creando un evento.',true);return false}
async function gh(path,opt={}){if(!requireToken())throw new Error('Token API GitHub non inserito.');return OWGithub.request(config,path,opt)}
function openAccess(mode){
  accessMode=mode;
  $('eventAccessTitle').textContent=mode==='new'?'Nuovo evento':'Apri evento';
  $('eventAccessHint').textContent=mode==='new'?'Inserisci il codice evento e il token API GitHub.':'Inserisci il codice evento e il token API GitHub.';
  $('eventCodeInput').value=mode==='new'?'':state.id;
  $('eventTokenInput').value=config.token||'';
  $('eventAccessConfirmBtn').textContent=mode==='new'?'Crea evento':'Apri evento';
  $('eventAccessMessage').textContent='';
  $('eventAccessDialog').showModal()
}
async function confirmAccess(){
  const c=code($('eventCodeInput').value),token=$('eventTokenInput').value.trim();
  if(!c||!token){$('eventAccessMessage').textContent='Codice evento e token API sono obbligatori.';return false}
  config.token=token;OWStorage.saveGithubConfig(config);renderHeader();
  if(accessMode==='new'){
    state=blank();state.id=c;state.createdAt=new Date().toISOString();currentSha=null;dirty=true;render();status(`Evento ${c} pronto. Premi Salva per crearlo.`);return true
  }
  try{
    $('eventAccessConfirmBtn').disabled=true;
    const path=`events/${c}.json`,r=await gh(`/repos/${encodeURIComponent(config.owner)}/${encodeURIComponent(config.repo)}/contents/${path}?ref=${encodeURIComponent(config.branch)}`),data=JSON.parse(unb64(r.content));
    state={...blank(),...data,event:{...blank().event,...(data.event||{})},refereeNotes:{...blank().refereeNotes,...(data.refereeNotes||{})}};
    delete state.secret;state.id=c;currentSha=r.sha;dirty=false;render();status(`Evento ${c} aperto.`);return true
  }catch(e){$('eventAccessMessage').textContent=e.message;return false}finally{$('eventAccessConfirmBtn').disabled=false}
}
async function save(){if(!state.id){status('Crea o apri prima un evento.',true);return}if(!requireToken())return;const btn=$('saveEventBtn');btn.disabled=true;btn.textContent='Salvataggio…';try{const data=structuredClone(state);delete data.secret;data.version=3;data.savedAt=new Date().toISOString();data.createdAt=data.createdAt||data.savedAt;const body={message:`${currentSha?'Aggiorna':'Crea'} evento ${state.id}`,content:b64(JSON.stringify(data,null,2)),branch:config.branch};if(currentSha)body.sha=currentSha;const r=await gh(`/repos/${encodeURIComponent(config.owner)}/${encodeURIComponent(config.repo)}/contents/events/${code(state.id)}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});currentSha=r?.content?.sha||currentSha;state.savedAt=data.savedAt;state.createdAt=data.createdAt;dirty=false;btn.textContent='⇩ Salva';renderHeader();status(`Evento ${state.id} salvato su GitHub.`)}catch(e){btn.textContent='● Salva';status(e.message,true)}finally{btn.disabled=false}}
function bind(){[['eventName','name'],['eventDate','date'],['eventVenue','venue'],['eventNotes','notes'],['pathNotes','pathNotes'],['athleteTotal','athleteTotal'],['athleteDescription','athleteDescription']].forEach(([id,k])=>{const el=$(id);el.value=state.event[k]??'';el.oninput=e=>{state.event[k]=e.target.type==='number'?Number(e.target.value||0):e.target.value;mark()}});$('briefingAthletes').value=state.refereeNotes.briefingAthletes||'';$('briefingJury').value=state.refereeNotes.briefingJury||'';$('briefingAthletes').oninput=e=>{state.refereeNotes.briefingAthletes=e.target.value;mark()};$('briefingJury').oninput=e=>{state.refereeNotes.briefingJury=e.target.value;mark()}}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function item(title,meta,onEdit,onDel,extra=''){const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="item-main"><div class="item-title">${esc(title)}</div><div class="item-meta">${esc(meta)}</div>${extra}</div><div class="item-actions"><button class="edit">Modifica</button><button class="danger del">Elimina</button></div>`;d.querySelector('.edit').onclick=onEdit;d.querySelector('.del').onclick=onDel;return d}
function empty(box,text){box.innerHTML=`<div class="empty">${esc(text)}</div>`}
function renderDepartures(){const box=$('departureList');box.innerHTML='';if(!state.event.athleteDepartures.length)return empty(box,'Nessuna partenza inserita.');state.event.athleteDepartures.forEach(x=>box.append(item(x.name||'Partenza',`${x.time||''}${x.athletes?` · ${x.athletes} atleti`:''}${x.numbers?` · Numeri: ${x.numbers}`:''}${x.notes?`\n${x.notes}`:''}`,()=>editDeparture(x.id),()=>{state.event.athleteDepartures=state.event.athleteDepartures.filter(y=>y.id!==x.id);mark();renderDepartures()})))}
function renderTimeline(){const box=$('timelineList');box.innerHTML='';if(!state.timeline.length)return empty(box,'Nessuna fase inserita.');state.timeline.forEach(x=>box.append(item(`${x.time||'--:--'} · ${x.title||'Fase'}`,`${x.place||''}${x.notes?`\n${x.notes}`:''}`,()=>editTimeline(x.id),()=>{state.timeline=state.timeline.filter(y=>y.id!==x.id);mark();renderTimeline()})))}
function renderOfficials(){const box=$('officialList');box.innerHTML='';if(!state.officials.length)return empty(box,'Nessun UG inserito.');state.officials.forEach(x=>box.append(item(x.name||'UG senza nome',x.notes||'',()=>editOfficial(x.id),()=>{state.officials=state.officials.filter(y=>y.id!==x.id);state.roleCategories.forEach(c=>(c.roles||[]).forEach(r=>r.officialIds=(r.officialIds||[]).filter(id=>id!==x.id)));mark();render()})))}
function renderRoles(){const box=$('roleCategoryList');box.innerHTML='';if(!state.roleCategories.length)return empty(box,'Nessuna categoria ruoli.');state.roleCategories.forEach(cat=>{const card=document.createElement('div');card.className='role-card';card.innerHTML=`<div class="role-head"><input class="cat-name" value="${esc(cat.name||'Categoria')}"><button class="add-role primary">＋ Ruolo</button><button class="del-cat danger">Elimina</button></div><div class="roles"></div>`;card.querySelector('.cat-name').oninput=e=>{cat.name=e.target.value;mark()};card.querySelector('.add-role').onclick=()=>{cat.roles=cat.roles||[];cat.roles.push({id:uid(),name:'Nuovo ruolo',officialIds:[]});mark();renderRoles()};card.querySelector('.del-cat').onclick=()=>{state.roleCategories=state.roleCategories.filter(x=>x.id!==cat.id);mark();renderRoles()};const roles=card.querySelector('.roles');(cat.roles||[]).forEach(r=>{const row=document.createElement('div');row.className='role-row';const opts=state.officials.map(o=>`<option value="${o.id}" ${(r.officialIds||[]).includes(o.id)?'selected':''}>${esc(o.name)}</option>`).join('');row.innerHTML=`<input class="role-name" value="${esc(r.name||'')}"><select class="role-off" multiple size="${Math.min(4,Math.max(2,state.officials.length))}">${opts}</select><button class="danger">Elimina</button>`;row.querySelector('.role-name').oninput=e=>{r.name=e.target.value;mark()};row.querySelector('.role-off').onchange=e=>{r.officialIds=[...e.target.selectedOptions].map(o=>o.value);mark()};row.querySelector('button').onclick=()=>{cat.roles=cat.roles.filter(x=>x.id!==r.id);mark();renderRoles()};roles.append(row)});box.append(card)})}
function renderChecklist(){const box=$('checklistBox');box.innerHTML='';const list=state.refereeNotes.checklist||[];if(!list.length)return empty(box,'Checklist vuota.');list.forEach(x=>{const d=document.createElement('div');d.className='checklist-row';d.innerHTML=`<input type="checkbox" ${x.checked?'checked':''}><span>${esc(x.label)}</span><button class="danger">Elimina</button>`;d.querySelector('input').onchange=e=>{x.checked=e.target.checked;mark()};d.querySelector('button').onclick=()=>{state.refereeNotes.checklist=list.filter(y=>y.id!==x.id);mark();renderChecklist()};box.append(d)})}
function fields(title,defs,values,saveFn){editCtx={defs,saveFn};$('editTitle').textContent=title;const box=$('editFields');box.innerHTML='';defs.forEach(([k,label,type])=>{const l=document.createElement('label');if(type==='textarea')l.className='wide';l.innerHTML=`${label}${type==='textarea'?`<textarea data-key="${k}">${esc(values[k]||'')}</textarea>`:`<input data-key="${k}" type="${type||'text'}" value="${esc(values[k]||'')}">`}`;box.append(l)});$('editDialog').showModal()}
function editDeparture(id){let x=state.event.athleteDepartures.find(y=>y.id===id);if(!x){x={id:uid(),name:'Partenza',time:'',athletes:'',numbers:'',notes:''};state.event.athleteDepartures.push(x)}fields('Partenza',[['name','Nome'],['time','Orario','time'],['athletes','Numero atleti','number'],['numbers','Numeri'],['notes','Note','textarea']],x,v=>Object.assign(x,v))}
function editTimeline(id){let x=state.timeline.find(y=>y.id===id);if(!x){x={id:uid(),time:'',title:'',place:'',notes:''};state.timeline.push(x)}fields('Fase timeline',[['time','Orario','time'],['title','Titolo'],['place','Luogo'],['notes','Note','textarea']],x,v=>Object.assign(x,v))}
function editOfficial(id){let x=state.officials.find(y=>y.id===id);if(!x){x={id:uid(),name:'',notes:''};state.officials.push(x)}fields('Ufficiale Gara',[['name','Nome e cognome'],['notes','Note','textarea']],x,v=>Object.assign(x,v))}
function saveEdit(){if(!editCtx)return;const v={};$('editFields').querySelectorAll('[data-key]').forEach(e=>v[e.dataset.key]=e.type==='number'?Number(e.value||0):e.value);editCtx.saveFn(v);editCtx=null;mark();render()}
function addChecklist(){const i=$('checklistInput'),v=i.value.trim();if(!v)return;state.refereeNotes.checklist.push({id:uid(),label:v,checked:false});i.value='';mark();renderChecklist()}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('hidden',x.id!==`view-${v}`));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v))}
function pdf(){const roles=state.roleCategories.map(c=>`<h3>${esc(c.name)}</h3>${(c.roles||[]).map(r=>`<p><b>${esc(r.name)}</b>: ${esc(state.officials.filter(o=>(r.officialIds||[]).includes(o.id)).map(o=>o.name).join(', ')||'—')}</p>`).join('')}`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;padding:32px;color:#18232d}h1{margin-bottom:4px}h2{border-bottom:1px solid #ccc;padding-bottom:5px;margin-top:28px}table{width:100%;border-collapse:collapse}td,th{padding:7px;border-bottom:1px solid #ddd;text-align:left}.muted{color:#666;white-space:pre-wrap}</style></head><body><h1>${esc(state.event.name)}</h1><div>${esc(state.event.date)} · ${esc(state.event.venue)}</div><h2>Evento</h2><p class="muted">${esc(state.event.notes)}</p><p><b>Atleti:</b> ${state.event.athleteTotal||0}</p><p class="muted">${esc(state.event.athleteDescription)}</p><h2>Timeline</h2><table>${state.timeline.map(x=>`<tr><td>${esc(x.time)}</td><td><b>${esc(x.title)}</b><br>${esc(x.place)}</td><td>${esc(x.notes)}</td></tr>`).join('')}</table><h2>Ufficiali Gara</h2>${state.officials.map(o=>`<p><b>${esc(o.name)}</b> ${esc(o.notes)}</p>`).join('')}<h2>Ruoli</h2>${roles}<h2>Briefing</h2><h3>Atleti</h3><p class="muted">${esc(state.refereeNotes.briefingAthletes)}</p><h3>Giuria</h3><p class="muted">${esc(state.refereeNotes.briefingJury)}</p></body></html>`;const f=$('pdfFrame');f.srcdoc=html;$('pdfDialog').showModal()}
function render(){bind();renderHeader();renderDepartures();renderTimeline();renderOfficials();renderRoles();renderChecklist();$('saveEventBtn').textContent=dirty?'● Salva':'⇩ Salva'}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('newEventBtn').onclick=()=>openAccess('new');$('openEventBtn').onclick=()=>openAccess('open');$('eventAccessConfirmBtn').onclick=async e=>{e.preventDefault();if(await confirmAccess())$('eventAccessDialog').close()};$('saveEventBtn').onclick=save;$('addDepartureBtn').onclick=()=>editDeparture();$('addTimelineBtn').onclick=()=>editTimeline();$('addOfficialBtn').onclick=()=>editOfficial();$('addRoleCategoryBtn').onclick=()=>{state.roleCategories.push({id:uid(),name:'Nuova categoria',roles:[]});mark();renderRoles()};$('editSaveBtn').onclick=e=>{e.preventDefault();saveEdit();$('editDialog').close()};$('addChecklistBtn').onclick=addChecklist;$('checklistInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addChecklist()}};$('pdfBtn').onclick=pdf;$('closePdfBtn').onclick=()=>$('pdfDialog').close();$('printPdfBtn').onclick=()=>$('pdfFrame').contentWindow.print();render();if(!config.token)status('Premi Nuovo o Apri e inserisci codice evento e token API GitHub.');
})();
