(() => {
const $=id=>document.getElementById(id), uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blank=()=>({version:4,id:'',createdAt:null,savedAt:null,roleSubcategoriesEnabled:false,event:{name:'Nuova gara di nuoto',date:'',venue:'',notes:'',pathNotes:'',athleteTotal:0,athleteDescription:'',athleteDepartures:[]},timeline:[],officials:[],roleCategories:[],refereeNotes:{briefingAthletes:'',briefingJury:'',checklist:[]}});
let state=blank(),dirty=false,editCtx=null;
const status=(t,e=false)=>{const n=$('status');n.textContent=t||'';n.style.color=e?'var(--danger)':'var(--muted)';if(t)setTimeout(()=>{if(n.textContent===t)n.textContent=''},4500)};
const normalize=data=>{const b=blank();const x={...b,...data,event:{...b.event,...(data?.event||{})},refereeNotes:{...b.refereeNotes,...(data?.refereeNotes||{})}};x.roleSubcategoriesEnabled=!!x.roleSubcategoriesEnabled;x.roleCategories=(x.roleCategories||[]).map(c=>({...c,subcategories:Array.isArray(c.subcategories)?c.subcategories:[],roles:(c.roles||[]).map(r=>({...r,officialIds:Array.isArray(r.officialIds)?r.officialIds:[],officialIdsBySubcategory:r.officialIdsBySubcategory||{}}))}));return x};
function show(id){['loginView','appView'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function showHome(){state=blank();dirty=false;$('editorView').classList.add('hidden');$('homeView').classList.remove('hidden');$('homeBtn').classList.add('hidden');$('pageTitle').textContent='Gestionale OW';$('pageSubtitle').textContent='Eventi condivisi';loadEvents()}
async function openEvent(code){try{const data=await OWDatabase.getEvent(code);if(!data)throw new Error('Evento non trovato');state=normalize(data);dirty=false;$('homeView').classList.add('hidden');$('editorView').classList.remove('hidden');$('homeBtn').classList.remove('hidden');render();status(`Evento ${code} aperto.`)}catch(e){status(e.message,true)}}
async function loadEvents(){const box=$('eventList');box.innerHTML='<div class="empty">Caricamento…</div>';try{const rows=await OWDatabase.listEvents();box.innerHTML='';if(!rows?.length){box.innerHTML='<div class="empty">Nessun evento.</div>';return}rows.forEach(e=>{const d=document.createElement('article');d.className='card event-card';d.innerHTML=`<div class="event-name">${esc(e.name||e.code)}</div><div class="event-meta">${esc(e.code)}${e.event_date?` · ${esc(e.event_date)}`:''}${e.venue?` · ${esc(e.venue)}`:''}${Number.isFinite(e.athlete_total)?` · ${e.athlete_total} atleti`:''}</div><div class="event-actions"><button class="open primary">Apri</button><button class="delete danger">Elimina</button></div>`;d.querySelector('.open').onclick=()=>openEvent(e.code);d.querySelector('.delete').onclick=async()=>{if(!confirm(`Eliminare ${e.code}?`))return;try{await OWDatabase.deleteEvent(e.code);status(`Evento ${e.code} eliminato.`);loadEvents()}catch(err){status(err.message,true)}};box.append(d)})}catch(e){box.innerHTML=`<div class="empty error">${esc(e.message)}</div>`}}
function mark(){dirty=true;$('saveEventBtn').textContent='● Salva'}
function bindFields(){[['eventName','name'],['eventDate','date'],['eventVenue','venue'],['eventNotes','notes'],['pathNotes','pathNotes'],['athleteTotal','athleteTotal'],['athleteDescription','athleteDescription']].forEach(([id,k])=>{const el=$(id);el.value=state.event[k]??'';el.oninput=e=>{state.event[k]=e.target.type==='number'?Number(e.target.value||0):e.target.value;mark()}});$('eventCode').value=state.id;$('briefingAthletes').value=state.refereeNotes.briefingAthletes||'';$('briefingJury').value=state.refereeNotes.briefingJury||'';$('briefingAthletes').oninput=e=>{state.refereeNotes.briefingAthletes=e.target.value;mark()};$('briefingJury').oninput=e=>{state.refereeNotes.briefingJury=e.target.value;mark()}}
function item(title,meta,onEdit,onDel){const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="item-main"><div class="item-title">${esc(title)}</div><div class="item-meta">${esc(meta)}</div></div><div class="item-actions"><button class="edit">Modifica</button><button class="danger del">Elimina</button></div>`;d.querySelector('.edit').onclick=onEdit;d.querySelector('.del').onclick=onDel;return d}
function empty(box,text){box.innerHTML=`<div class="empty">${esc(text)}</div>`}
function fields(title,defs,values,saveFn){editCtx={defs,saveFn};$('editTitle').textContent=title;const box=$('editFields');box.innerHTML='';defs.forEach(([k,label,type])=>{const l=document.createElement('label');if(type==='textarea')l.className='wide';l.innerHTML=`${label}${type==='textarea'?`<textarea data-key="${k}">${esc(values[k]||'')}</textarea>`:`<input data-key="${k}" type="${type||'text'}" value="${esc(values[k]??'')}">`}`;box.append(l)});$('editDialog').showModal()}
function editDeparture(id){let x=state.event.athleteDepartures.find(y=>y.id===id);if(!x){x={id:uid(),name:'Partenza',time:'',athletes:0,numbers:'',notes:''};state.event.athleteDepartures.push(x)}fields('Partenza',[['name','Nome'],['time','Orario','time'],['athletes','Numero atleti','number'],['numbers','Numeri'],['notes','Note','textarea']],x,v=>Object.assign(x,v))}
function editTimeline(id){let x=state.timeline.find(y=>y.id===id);if(!x){x={id:uid(),time:'',title:'',place:'',notes:''};state.timeline.push(x)}fields('Fase timeline',[['time','Orario','time'],['title','Titolo'],['place','Luogo'],['notes','Note','textarea']],x,v=>Object.assign(x,v))}
function editOfficial(id){let x=state.officials.find(y=>y.id===id);if(!x){x={id:uid(),name:'',notes:''};state.officials.push(x)}fields('Ufficiale Gara',[['name','Nome e cognome'],['notes','Note','textarea']],x,v=>Object.assign(x,v))}
function renderDepartures(){const b=$('departureList');b.innerHTML='';if(!state.event.athleteDepartures.length)return empty(b,'Nessuna partenza inserita.');state.event.athleteDepartures.forEach(x=>b.append(item(x.name||'Partenza',`${x.time||''}${x.athletes?` · ${x.athletes} atleti`:''}${x.notes?`\n${x.notes}`:''}`,()=>editDeparture(x.id),()=>{state.event.athleteDepartures=state.event.athleteDepartures.filter(y=>y.id!==x.id);mark();renderDepartures()})))}
function renderTimeline(){const b=$('timelineList');b.innerHTML='';if(!state.timeline.length)return empty(b,'Nessuna fase inserita.');state.timeline.forEach(x=>b.append(item(`${x.time||'--:--'} · ${x.title||'Fase'}`,`${x.place||''}${x.notes?`\n${x.notes}`:''}`,()=>editTimeline(x.id),()=>{state.timeline=state.timeline.filter(y=>y.id!==x.id);mark();renderTimeline()})))}
function renderOfficials(){const b=$('officialList');b.innerHTML='';if(!state.officials.length)return empty(b,'Nessun UG inserito.');state.officials.forEach(x=>b.append(item(x.name||'UG senza nome',x.notes||'',()=>editOfficial(x.id),()=>{state.officials=state.officials.filter(y=>y.id!==x.id);state.roleCategories.forEach(c=>(c.roles||[]).forEach(r=>{r.officialIds=(r.officialIds||[]).filter(id=>id!==x.id);Object.keys(r.officialIdsBySubcategory||{}).forEach(k=>r.officialIdsBySubcategory[k]=(r.officialIdsBySubcategory[k]||[]).filter(id=>id!==x.id))}));mark();render()})))}
function assignmentIds(r,s){if(!s)return r.officialIds||(r.officialIds=[]);r.officialIdsBySubcategory=r.officialIdsBySubcategory||{};return r.officialIdsBySubcategory[s]||(r.officialIdsBySubcategory[s]=[])}
function renderAssignment(parent,r,s,label){const ids=assignmentIds(r,s),w=document.createElement('div');w.className='assignment-group';w.innerHTML=`<div class="assignment-title">${esc(label||'UG assegnati')}</div><div class="selected-officials"></div><select><option value="">Assegna UG...</option></select>`;const selected=w.querySelector('.selected-officials');ids.forEach(id=>{const o=state.officials.find(x=>x.id===id),p=document.createElement('span');p.className='selected-official';p.innerHTML=`<span>${esc(o?.name||'UG')}</span><button type="button" class="danger">×</button>`;p.querySelector('button').onclick=()=>{const next=ids.filter(x=>x!==id);if(!s)r.officialIds=next;else r.officialIdsBySubcategory[s]=next;mark();renderRoles()};selected.append(p)});const sel=w.querySelector('select');state.officials.filter(o=>!ids.includes(o.id)).forEach(o=>{const op=document.createElement('option');op.value=o.id;op.textContent=o.name;sel.append(op)});sel.onchange=e=>{if(!e.target.value)return;ids.push(e.target.value);mark();renderRoles()};parent.append(w)}
function renderRoles(){const b=$('roleCategoryList');b.innerHTML='';const settings=document.createElement('div');settings.className='card';settings.innerHTML=`<label><span><strong>Usa sottocategorie dei ruoli</strong></span><input id="subToggle" type="checkbox" ${state.roleSubcategoriesEnabled?'checked':''}></label>`;settings.querySelector('input').onchange=e=>{state.roleSubcategoriesEnabled=e.target.checked;mark();renderRoles()};b.append(settings);if(!state.roleCategories.length)return;state.roleCategories.forEach(cat=>{cat.roles=cat.roles||[];cat.subcategories=cat.subcategories||[];const card=document.createElement('div');card.className='role-card';card.innerHTML=`<div class="role-head"><input class="cat-name" value="${esc(cat.name||'Categoria')}"><button class="add-role primary">＋ Ruolo</button><button class="add-sub">＋ Sottocategoria</button><button class="del-cat danger">Elimina</button></div><div class="subs"></div><div class="roles"></div>`;card.querySelector('.cat-name').oninput=e=>{cat.name=e.target.value;mark()};card.querySelector('.add-role').onclick=()=>{cat.roles.push({id:uid(),name:'Nuovo ruolo',officialIds:[],officialIdsBySubcategory:{}});mark();renderRoles()};card.querySelector('.add-sub').onclick=()=>{cat.subcategories.push({id:uid(),name:'Nuova sottocategoria'});state.roleSubcategoriesEnabled=true;mark();renderRoles()};card.querySelector('.del-cat').onclick=()=>{state.roleCategories=state.roleCategories.filter(x=>x.id!==cat.id);mark();renderRoles()};const subs=card.querySelector('.subs');if(state.roleSubcategoriesEnabled)cat.subcategories.forEach(s=>{const row=document.createElement('div');row.className='subcategory-row';row.innerHTML=`<input value="${esc(s.name)}"><button class="danger">×</button>`;row.querySelector('input').oninput=e=>{s.name=e.target.value;mark()};row.querySelector('button').onclick=()=>{cat.subcategories=cat.subcategories.filter(x=>x.id!==s.id);cat.roles.forEach(r=>delete (r.officialIdsBySubcategory||{})[s.id]);mark();renderRoles()};subs.append(row)});const roles=card.querySelector('.roles');cat.roles.forEach(r=>{const row=document.createElement('div');row.className='role-row';row.innerHTML=`<input class="role-name" value="${esc(r.name||'')}"><div class="assignment-panel"></div><button class="danger role-delete">Elimina</button>`;row.querySelector('.role-name').oninput=e=>{r.name=e.target.value;mark()};const panel=row.querySelector('.assignment-panel');const groups=state.roleSubcategoriesEnabled&&cat.subcategories.length?cat.subcategories:[{id:'',name:'UG assegnati'}];groups.forEach(g=>renderAssignment(panel,r,g.id,g.name));row.querySelector('.role-delete').onclick=()=>{cat.roles=cat.roles.filter(x=>x.id!==r.id);mark();renderRoles()};roles.append(row)});b.append(card)})}
function renderChecklist(){const b=$('checklistBox');b.innerHTML='';const list=state.refereeNotes.checklist||[];if(!list.length)return empty(b,'Checklist vuota.');list.forEach(x=>{const d=document.createElement('div');d.className='checklist-row';d.innerHTML=`<input type="checkbox" ${x.checked?'checked':''}><span>${esc(x.label)}</span><button class="danger">Elimina</button>`;d.querySelector('input').onchange=e=>{x.checked=e.target.checked;mark()};d.querySelector('button').onclick=()=>{state.refereeNotes.checklist=list.filter(y=>y.id!==x.id);mark();renderChecklist()};b.append(d)})}
function render(){bindFields();renderDepartures();renderTimeline();renderOfficials();renderRoles();renderChecklist();$('pageTitle').textContent=state.event.name||state.id||'Gestionale OW';$('pageSubtitle').textContent=[state.id,state.event.venue,state.event.date].filter(Boolean).join(' · ');$('saveEventBtn').textContent=dirty?'● Salva':'⇩ Salva'}
async function save(){if(!state.id)return;const btn=$('saveEventBtn');btn.disabled=true;btn.textContent='Salvataggio…';try{const now=new Date().toISOString(),data=structuredClone(state);data.version=4;data.createdAt=data.createdAt||now;data.savedAt=now;const saved=await OWDatabase.saveEvent(data);state=normalize(saved);dirty=false;render();status(`Evento ${state.id} salvato.`)}catch(e){status(e.message,true)}finally{btn.disabled=false}}
function saveEdit(){if(!editCtx)return;const v={};$('editFields').querySelectorAll('[data-key]').forEach(e=>v[e.dataset.key]=e.type==='number'?Number(e.value||0):e.value);editCtx.saveFn(v);editCtx=null;mark();render()}
async function init(){const s=await OWAuth.session();if(!s){show('loginView');return}show('appView');$('userBadge').textContent=s.user.email||'Utente';showHome()}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';try{await OWAuth.signIn($('loginEmail').value.trim(),$('loginPassword').value);await init()}catch(err){$('loginError').textContent=err.message}};
$('logoutBtn').onclick=async()=>{await OWAuth.signOut();location.reload()};$('homeBtn').onclick=showHome;$('refreshBtn').onclick=loadEvents;$('newEventBtn').onclick=()=>{$('newEventCode').value='';$('newEventName').value='';$('newEventError').textContent='';$('newEventDialog').showModal()};$('createEventBtn').onclick=e=>{e.preventDefault();const code=$('newEventCode').value.trim().replace(/[^A-Za-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'');if(!code){$('newEventError').textContent='Inserisci un codice evento.';return}state=blank();state.id=code;state.event.name=$('newEventName').value.trim()||'Nuova gara di nuoto';state.createdAt=new Date().toISOString();dirty=true;$('newEventDialog').close();$('homeView').classList.add('hidden');$('editorView').classList.remove('hidden');$('homeBtn').classList.remove('hidden');render()};
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(x=>x.classList.toggle('hidden',x.id!==`view-${b.dataset.view}`));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x===b))});$('saveEventBtn').onclick=save;$('addDepartureBtn').onclick=()=>editDeparture();$('addTimelineBtn').onclick=()=>editTimeline();$('addOfficialBtn').onclick=()=>editOfficial();$('addRoleCategoryBtn').onclick=()=>{state.roleCategories.push({id:uid(),name:'Nuova categoria',subcategories:[],roles:[]});mark();renderRoles()};$('editSaveBtn').onclick=e=>{e.preventDefault();saveEdit();$('editDialog').close()};$('addChecklistBtn').onclick=()=>{const i=$('checklistInput'),v=i.value.trim();if(!v)return;state.refereeNotes.checklist.push({id:uid(),label:v,checked:false});i.value='';mark();renderChecklist()};
init().catch(e=>{show('loginView');$('loginError').textContent=e.message});
})();
